<?php

namespace StudentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends EntityRepository
{
    /*
     * get max position
     */
    function getPositionMax(){
        $select = $this->createQueryBuilder('s');
        $select
                ->select('MAX(s.position)');
        return $select->getQuery()->getSingleScalarResult();
    }
    /*
     * get min position
     */
    function getPositionMin(){
        $select = $this->createQueryBuilder('s');
        $select
                ->select('MIN(s.position)');
        return $select->getQuery()->getSingleScalarResult();
    }
}
