<?php

namespace StudentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
     * Get list news in FO
     *
     * @param object $category category
     *
     * @return array
     */
    public function getUser($category)
    {

        $select = $this->createQueryBuilder('u')
                ->join('n.newsPermission', 'np', Expr\Join::WITH, 'np.type = 1')
                ->where('n.displayType != 3 AND n.status = 1')
                ->andWhere('np.group IN(:group)')
                ->andWhere('n.datePublication <= :now')
                ->setParameter('group', $groupUser->toArray())
                ->setParameter('now', new \DateTime('now'))
                ->orderBy('n.position', 'ASC')
                ->orderBy('n.created', 'DESC');
        if ($category) {
            $select->andWhere('n.category = :category')
                    ->setParameter('category', $category);
        }

        return $select->getQuery()->getResult();
    }
    
}
